# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 084b9e9fe48552d76739fd6222804bf7ad2dad36ab973fde0467d8e3d76a4ac1f541156711484d1820f301a1dbb6dd155b5eafa588a1c0dccd6fd86a90688949

test:
  secret_key_base: d5d4111d8b453349a9b21371618827e99e51312dc10cf8340d7cb58d7c831af88d40dc72ad6310703e383df3262ed5b929f11ac2bc072d950ed6bfbaf2d38126

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
